variables:
    REPO: aistcpsec/tee-dev

stages:
    - build
    - rootfs
    - trigger

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

tee-dev-sgx_2.10:
    tags:
        - fast-shells
    stage: build
    script:
        - docker pull aistcpsec/tee-distro-dev:x64-20.04
        - docker build --build-arg VERSION=2.10 --build-arg DEBUG_DATE=$(date +%s)
          --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:sgx-2.10 ./sgx/2.10
        - docker push ${REPO}:sgx-2.10

tee-dev-optee_3.9.0:
#    only:
#        - todo # skip this ci
    tags:
        - fast-shells
    stage: build
    script:
        - docker pull aistcpsec/tee-distro-dev:arm64-20.04
        - docker build --build-arg VERSION=3.9.0 --build-arg DEBUG_DATE=$(date +%s)
          --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:optee-3.9.0 ./optee/3.9.0
        - docker push ${REPO}:optee-3.9.0

tee-dev-optee_3.10.0:
    tags:
        - fast-shells
    stage: build
    script:
        - docker pull aistcpsec/tee-distro-dev:arm64-20.04
        - docker build --build-arg VERSION=3.10.0 --build-arg DEBUG_DATE=$(date +%s) --rm -t
          ${REPO}:optee-3.10.0 ./optee/3.10.0
        - docker push ${REPO}:optee-3.10.0


tee-dev-optee_3.10.0_rpi3:
    tags:
        - fast-shells
    stage: build
    script:
        - docker pull aistcpsec/tee-distro-dev:arm64-20.04
        - docker build --build-arg VERSION=3.10.0 --build-arg DEBUG_DATE=$(date +%s) --rm -t
          ${REPO}:optee-3.10.0_rpi3 ./optee/3.10.0_rpi3
        - docker push ${REPO}:optee-3.10.0_rpi3

tee-dev-optee-3.10.0_rpi3_netboot_bootloader:
    tags:
        - fast-shells
    stage: rootfs
    script:
        - docker pull aistcpsec/tee-dev:optee-3.10.0_rpi3
        - docker build --build-arg VERSION=3.10.0 --build-arg DEBUG_DATE=$(date +%s) --rm -t
          ${REPO}:optee-3.10.0_rpi3_netboot_bootloader ./optee/3.10.0_rpi3_netboot_bootloader
        - docker push ${REPO}:optee-3.10.0_rpi3_netboot_bootloader

tee-dev-optee-3.10.0_rpi3_netboot_nfs:
    tags:
        - shell117
    stage: rootfs
    variables:
        NETBOOT_CONT_NME: rootfs-tar-container
        ROOTFS_FILE: arm64-20.04-rootfs-optee.tar.xz
    script:
        - docker pull aistcpsec/tee-distro-dev:rootfs-arm64-ubuntu-20.04-tar
        - docker pull aistcpsec/tee-dev:optee-3.10.0_rpi3
        - docker build --rm -t ${REPO}:optee-3.10.0_rpi3_netboot_nfs
           ./optee/3.10.0_rpi3_netboot_nfs
        - for i in {1..5}; do docker stop $NETBOOT_CONT_NME || true; done 
        - docker rm $NETBOOT_CONT_NME || true
        - docker run --privileged --cap-add=SYS_CHROOT --name $NETBOOT_CONT_NME
           -v $(pwd)/optee/3.10.0_rpi3_netboot_nfs:/mnt
           ${REPO}:optee-3.10.0_rpi3_netboot_nfs /bin/bash
           -c "/mnt/customize-rootfs.sh > /mnt/net-nfs.log &&
               cp /arm64-20.04-rootfs-optee.tar.xz /mnt/"
        - cat $(pwd)/optee/3.10.0_rpi3_netboot_nfs/net-nfs.log
        - docker push ${REPO}:optee-3.10.0_rpi3_netboot_nfs
        # - docker cp $NETBOOT_CONT_NME:/${ROOTFS_FILE} $CI_PROJECT_DIR/${ROOTFS_FILE}
        # - echo $(pwd) && ls -l $(pwd)/optee/3.10.0_rpi3_netboot_nfs/
        # - echo $CI_PROJECT_DIR && ls -l $CI_PROJECT_DIR
        # - cp $(pwd)/optee/3.10.0_rpi3_netboot_nfs/${ROOTFS_FILE}
        #    $CI_PROJECT_DIR/${ROOTFS_FILE}
        - for i in {1..5}; do docker stop $NETBOOT_CONT_NME || true; done
        - docker rm $NETBOOT_CONT_NME || true
    artifacts:
            paths:
                - $(pwd)/optee/3.10.0_rpi3_netboot_nfs/${ROOTFS_FILE}
            expire_in: 1 week


tee-dev-keystone_1.0.0:
    tags:
        - fast-shells
    stage: build
    script:
        - docker pull aistcpsec/tee-distro-dev:riscv-20.04
        - docker build --build-arg VERSION=v1.0.0 --build-arg DEBUG_DATE=$(date +%s) --rm -t
          ${REPO}:keystone-1.0.0 ./keystone/1.0.0
        - docker push ${REPO}:keystone-1.0.0

trigger_docker-taref-dev:
    variables:
        TOKEN: 29d9f4acb972460d03f8bd22e76880
    stage: trigger
    tags:
        - shell117
    script:
        - "curl -X POST --fail --retry 5 -F token=${TOKEN} -F ref=main -k
          https://192.168.100.100/api/v4/projects/132/trigger/pipeline"
