variables:
    REPO: aistcpsec/tee-dev

before_script:
    - docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWD}

tee-dev-sgx_2.10:
    tags:
        - shell115
    script:
        - docker pull ${REPO}:sgx-2.10
        - docker build --build-arg VERSION=2.10 --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:sgx-2.10 ./sgx/2.10
        - docker push ${REPO}:sgx-2.10

tee-dev-optee_3.9.0:
    tags:
        - shell117
    script:
        - docker pull ${REPO}:optee-3.9.0
        - docker build --build-arg VERSION=3.9.0 --build-arg DEBUG_DATE=$(date +%s) --build-arg CI_JOB_TOKEN=${CI_JOB_TOKEN} --rm -t ${REPO}:optee-3.9.0 ./optee/3.9.0
        - docker push ${REPO}:optee-3.9.0

tee-dev-optee_3.10.0:
    tags:
        - shell121
    script:
        - docker pull ${REPO}:optee-3.10.0 
        - docker build --build-arg VERSION=3.10.0 --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:optee-3.10.0 ./optee/3.10.0
        - docker push ${REPO}:optee-3.10.0

tee-dev-keystone_1.0.0:
    tags:
        - shell121
    script:
        - docker pull ${REPO}:keystone-1.0.0
        - docker build --build-arg VERSION=v1.0.0 --build-arg DEBUG_DATE=$(date +%s) --rm -t ${REPO}:keystone-1.0.0 ./keystone/1.0.0
        - docker push ${REPO}:keystone-1.0.0

